server:
  port: 8489
  servlet:
    context-path: /permission

spring:
  #Drui连接池#
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_permission?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    # 初始化大小，最小，最大
    initialSize: 3
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    validation-query-timeout: 30000
    validation-query: SELECT 'x' FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 配置监控统计拦截的filters
    filters: stat,wall,log4j2
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  #配置时区
  jackson:
    time-zone: GMT+8
  #redis连接池#

  redis:
    # Redis服务器地址 #
    host: 127.0.0.1
    # Redis服务器连接端口  #
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） #
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）  #
        max-wait: 2000ms
        # 连接池中的最大空闲连接  #
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 5000ms
  thymeleaf:
    cache: false
    enabled: false
#mybatis配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.wx.permission.model


logging:
  level:
    com:
      wx:
        permission:
         dao: debug

#配置过滤器白名单
exclusion:
  urls: /noAuth.jsp,/admin/login.page,/admin/index.page,/signin.jsp